[WIP] introduce reports with jinja
4383/kojak pull request #29
Opened 2019-04-09 16:27 UTC by 4383

Generate analyze reports by using jinja2 to
merge usages between CLI output and web html outputs

2019-04-09 16:28 UTC, 4383 commented
I need to add changes on tests so wait for the moment

2019-04-10 08:33 UTC, hobbestigrou requested changes

2019-04-10 08:33 UTC, hobbestigrou commented on kojak/templates/cli.txt
> +{{ module.imports|length }} {{ module.imports|length|pluralize("import")}}
I think it's now possible to use the pluralize from jinja.

2019-04-10 08:33 UTC, hobbestigrou commented on kojak/templates/cli.txt
> +{{ module.classes|length }} {{ module.classes|length|pluralize("class", "classes")}}
Same here.

2019-04-10 08:33 UTC, hobbestigrou commented on kojak/templates/cli.txt
> +- {{ analyze.imports }} {{ analyze.imports|pluralize("import") }}
Same here.

2019-04-10 08:33 UTC, hobbestigrou commented on kojak/templates/cli.txt
> +- {{ analyze.classes }} {{ analyze.classes|pluralize("class", "classes") }}
Same here.

2019-04-10 08:33 UTC, hobbestigrou commented on kojak/templates/cli/classes.txt
> +    Module {{ module.classes|length|pluralize("classe", "classes")}}:
Same here.

2019-04-10 08:33 UTC, hobbestigrou commented on kojak/templates/cli/imports.txt
> +    Module {{ module.imports|length|pluralize("import")}}:
Same here.

2019-04-10 14:05 UTC, hobbestigrou commented
Ok for me, I agree.

2019-04-10 14:06 UTC, hobbestigrou approved these changes

2019-04-10 14:06 UTC, merged